version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - ENV_FILE=./.env
    ports:
      - "8000:8000"
    command: uvicorn interfaces.api:app --host 0.0.0.0 --port 8000 --reload
