#!/bin/bash
# Generate a ready-to-use .env file for local/Docker launch.
# Run from the repo root: bash scripts/setup/generate_env.sh

set -e

TARGET=".env"

if [ -f "$TARGET" ]; then
  echo "⚠️  $TARGET already exists. Rename it first if you want a fresh one."
  exit 0
fi

# Generate random secrets
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
JWT_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")

cat > "$TARGET" <<EOF
# ============================================================
# JARVIS .env — auto-generated by scripts/setup/generate_env.sh
# ============================================================

ENVIRONMENT=production

# API
API_HOST=0.0.0.0
API_PORT=8000
API_WORKERS=2
API_RELOAD=false
API_DEBUG=false

# Security (auto-generated — keep secret)
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7

# OpenAI — EDIT THIS before starting
OPENAI_API_KEY=sk-your-openai-api-key-here
OPENAI_MODEL=gpt-4
OPENAI_MAX_TOKENS=2000
OPENAI_TEMPERATURE=0.7

# CORS — add your domain here for production
CORS_ORIGINS=http://localhost:3000,http://localhost:5173

# Database (optional — only needed with --profile full)
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=jarvis
POSTGRES_USER=jarvis
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://jarvis:${POSTGRES_PASSWORD}@postgres:5432/jarvis

# Redis (optional — only needed with --profile full)
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=

# Paths
MEMORY_BASE_PATH=./memory
RUNTIME_BASE_PATH=./runtime

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Feature Flags
ENABLE_WEBSOCKET=false
ENABLE_MULTI_USER=false

# Frontend
VITE_API_URL=http://localhost:8000
VITE_WS_URL=ws://localhost:8000
EOF

echo "✅  .env created with auto-generated secrets."
echo ""
echo "Next: edit OPENAI_API_KEY in .env, then run:"
echo "  docker compose up --build -d"
echo ""
echo "For full stack (with Postgres + Redis):"
echo "  docker compose --profile full up --build -d"
