"""Innovation entity for the domain layer."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from jarvis_core.shared.exceptions import DomainException
from jarvis_core.shared.utils import current_timestamp, generate_id


@dataclass
class Innovation:
    """Innovation entity representing creative ideas and improvements.

    Innovations capture novel approaches, process improvements, and creative
    solutions generated by the system or identified through analysis.
    """

    innovation_id: str = field(default_factory=lambda: generate_id("inn_"))
    title: str = ""
    description: str = ""
    category: str = "general"  # general, process, technical, strategic, learning
    impact_score: float = 0.5

    created_at: datetime = field(default_factory=current_timestamp)
    created_by: str = "system"
    status: str = "proposed"  # proposed, approved, implemented, rejected, archived
    implementation_notes: Optional[str] = None

    def __post_init__(self):
        """Validate innovation after initialization."""
        if not self.title:
            raise DomainException("Innovation title cannot be empty")
        if self.impact_score < 0.0 or self.impact_score > 1.0:
            raise DomainException("Impact score must be between 0.0 and 1.0")

    def mark_implemented(self, notes: Optional[str] = None) -> None:
        """Mark the innovation as implemented.

        Args:
            notes: Optional implementation notes

        Raises:
            DomainException: If innovation is rejected or already implemented
        """
        if self.status == "rejected":
            raise DomainException("Cannot implement rejected innovation")
        if self.status == "implemented":
            raise DomainException("Innovation already implemented")

        self.status = "implemented"
        if notes:
            self.implementation_notes = notes

    def approve(self) -> None:
        """Approve the innovation for implementation.

        Raises:
            DomainException: If innovation is rejected
        """
        if self.status == "rejected":
            raise DomainException("Cannot approve rejected innovation")

        self.status = "approved"

    def reject(self, reason: Optional[str] = None) -> None:
        """Reject the innovation.

        Args:
            reason: Optional rejection reason
        """
        self.status = "rejected"
        if reason:
            self.implementation_notes = f"Rejected: {reason}"

    def archive(self) -> None:
        """Archive the innovation."""
        self.status = "archived"

    def update_impact_score(self, new_score: float) -> None:
        """Update the impact score.

        Args:
            new_score: New impact score

        Raises:
            DomainException: If score is invalid
        """
        if new_score < 0.0 or new_score > 1.0:
            raise DomainException("Impact score must be between 0.0 and 1.0")

        self.impact_score = new_score

    def is_proposed(self) -> bool:
        """Check if innovation is in proposed status."""
        return self.status == "proposed"

    def is_approved(self) -> bool:
        """Check if innovation is approved."""
        return self.status == "approved"

    def is_implemented(self) -> bool:
        """Check if innovation is implemented."""
        return self.status == "implemented"

    def is_rejected(self) -> bool:
        """Check if innovation is rejected."""
        return self.status == "rejected"

    def is_high_impact(self) -> bool:
        """Check if innovation has high impact (>= 0.7).

        Returns:
            True if impact score is high
        """
        return self.impact_score >= 0.7

    def is_medium_impact(self) -> bool:
        """Check if innovation has medium impact (0.4 - 0.7).

        Returns:
            True if impact score is medium
        """
        return 0.4 <= self.impact_score < 0.7

    def is_low_impact(self) -> bool:
        """Check if innovation has low impact (< 0.4).

        Returns:
            True if impact score is low
        """
        return self.impact_score < 0.4

    def get_age_in_days(self) -> float:
        """Calculate the age of this innovation in days.

        Returns:
            Age in days
        """
        age = current_timestamp() - self.created_at
        return age.total_seconds() / 86400  # seconds per day

    def __str__(self) -> str:
        """String representation of the innovation."""
        return f"{self.title} ({self.status})"

    def __repr__(self) -> str:
        """Detailed representation of the innovation."""
        return (
            f"Innovation(id={self.innovation_id}, title={self.title}, "
            f"category={self.category}, impact={self.impact_score:.2f}, "
            f"status={self.status})"
        )
